/**
 * Generates a multi-page PDF resilience report from structured JSON data.
 * Uses jsPDF to render an A4 portrait document with executive summary,
 * SPOF inventory, namespace risk ranking, blast radius heatmap, and
 * prioritized recommendations.
 */
import type { ResilienceReport } from '@/services/api/reports';

/** A4 page constants in mm */
const PAGE_WIDTH = 210;
const PAGE_HEIGHT = 297;
const MARGIN = 20;
const CONTENT_WIDTH = PAGE_WIDTH - MARGIN * 2;
const FOOTER_Y = PAGE_HEIGHT - 12;

/** Color palette for health / risk levels */
const LEVEL_COLORS: Record<string, [number, number, number]> = {
  critical: [220, 38, 38],   // red-600
  poor: [220, 38, 38],
  high: [234, 88, 12],       // orange-600
  fair: [234, 88, 12],
  medium: [202, 138, 4],     // yellow-600
  low: [22, 163, 74],        // green-600
  good: [22, 163, 74],
  excellent: [22, 163, 74],
};

const COLOR_MUTED: [number, number, number] = [120, 120, 120];
const COLOR_LINE: [number, number, number] = [200, 200, 200];
const COLOR_BLACK: [number, number, number] = [0, 0, 0];
const COLOR_HEADER_BG: [number, number, number] = [243, 244, 246]; // gray-100

/**
 * Generate and download a resilience report PDF.
 * Dynamically imports jsPDF to keep the main bundle lean.
 */
export async function generateResiliencePDF(report: ResilienceReport): Promise<void> {
  const { jsPDF } = await import('jspdf');

  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4',
  });

  let y = MARGIN;
  let pageNumber = 1;

  // ── Helpers ──────────────────────────────────────────────────────────

  const addPageFooter = () => {
    doc.setFontSize(7);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(...COLOR_MUTED);
    doc.text(
      `Generated by Kubilitics | ${new Date(report.generated_at).toLocaleString()}`,
      MARGIN,
      FOOTER_Y,
    );
    doc.text(`Page ${pageNumber}`, PAGE_WIDTH - MARGIN, FOOTER_Y, { align: 'right' });
    doc.setTextColor(...COLOR_BLACK);
  };

  const addPage = () => {
    addPageFooter();
    doc.addPage();
    pageNumber++;
    y = MARGIN;
  };

  const checkPage = (needed: number) => {
    if (y + needed > PAGE_HEIGHT - 20) addPage();
  };

  const drawSectionTitle = (title: string) => {
    checkPage(20);
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...COLOR_BLACK);
    doc.text(title, MARGIN, y);
    y += 2;
    doc.setDrawColor(...COLOR_LINE);
    doc.line(MARGIN, y, MARGIN + CONTENT_WIDTH, y);
    y += 6;
  };

  const drawTableHeader = (columns: { label: string; x: number }[]) => {
    // Header background
    doc.setFillColor(...COLOR_HEADER_BG);
    doc.rect(MARGIN, y - 3.5, CONTENT_WIDTH, 5, 'F');

    doc.setFontSize(7.5);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...COLOR_MUTED);
    for (const col of columns) {
      doc.text(col.label, col.x, y);
    }
    y += 3;
    doc.setDrawColor(...COLOR_LINE);
    doc.line(MARGIN, y, MARGIN + CONTENT_WIDTH, y);
    y += 3;
    doc.setTextColor(...COLOR_BLACK);
  };

  // ── Page 1: Title + Executive Summary ────────────────────────────────

  // Title block
  doc.setFontSize(22);
  doc.setFont('helvetica', 'bold');
  doc.text('Kubilitics Resilience Report', MARGIN, y);
  y += 8;

  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(...COLOR_MUTED);
  doc.text(
    `${report.cluster_name} | Generated: ${new Date(report.generated_at).toLocaleString()}`,
    MARGIN,
    y,
  );
  doc.setTextColor(...COLOR_BLACK);
  y += 12;

  // Health score — large colored number
  const exec = report.executive_summary;
  const healthColor = LEVEL_COLORS[exec.health_level] ?? COLOR_BLACK;

  doc.setFontSize(36);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...healthColor);
  doc.text(`${Math.round(exec.health_score)}`, MARGIN, y);

  doc.setFontSize(14);
  doc.text('/100', MARGIN + doc.getTextWidth(`${Math.round(exec.health_score)}`) * (36 / 14) + 2, y);
  // Reset: actually compute the x properly
  const scoreText = `${Math.round(exec.health_score)}`;
  doc.setFontSize(36);
  const scoreWidth = doc.getTextWidth(scoreText);
  doc.setFontSize(14);
  doc.text('/100', MARGIN + scoreWidth + 2, y);

  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text(`Health: ${exec.health_level.toUpperCase()}`, MARGIN + scoreWidth + 22, y);
  doc.setTextColor(...COLOR_BLACK);
  y += 14;

  // Key metrics
  drawSectionTitle('Executive Summary');

  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  const summaryMetrics = [
    ['Total Workloads', String(exec.total_workloads)],
    ['Single Points of Failure', `${exec.total_spofs} (${exec.critical_spofs} critical)`],
    ['Namespaces at Risk', String(exec.namespaces_at_risk)],
  ];
  for (const [label, value] of summaryMetrics) {
    doc.setFont('helvetica', 'bold');
    doc.text(`${label}:`, MARGIN, y);
    doc.setFont('helvetica', 'normal');
    doc.text(value, MARGIN + 45, y);
    y += 5.5;
  }
  y += 3;

  // Top risk
  if (exec.top_risk) {
    doc.setFontSize(9);
    doc.setFont('helvetica', 'bold');
    doc.text('Top Risk:', MARGIN, y);
    y += 4.5;
    doc.setFont('helvetica', 'normal');
    const riskLines: string[] = doc.splitTextToSize(exec.top_risk, CONTENT_WIDTH);
    for (const line of riskLines) {
      doc.text(line, MARGIN, y);
      y += 4;
    }
    y += 5;
  }

  // ── Page 2: SPOF Inventory ───────────────────────────────────────────

  addPage();
  drawSectionTitle('Single Points of Failure');

  if (report.spof_inventory.items.length === 0) {
    doc.setFontSize(9);
    doc.setFont('helvetica', 'italic');
    doc.text('No single points of failure detected.', MARGIN, y);
    y += 7;
  } else {
    const spofColumns = [
      { label: 'Resource', x: MARGIN },
      { label: 'Kind', x: MARGIN + 55 },
      { label: 'Namespace', x: MARGIN + 75 },
      { label: 'Blast Radius', x: MARGIN + 105 },
      { label: 'Reason', x: MARGIN + 128 },
    ];
    drawTableHeader(spofColumns);

    doc.setFontSize(7.5);
    doc.setFont('helvetica', 'normal');
    const spofItems = report.spof_inventory.items.slice(0, 20);
    for (const item of spofItems) {
      checkPage(6);
      doc.text(item.name.slice(0, 30), MARGIN, y);
      doc.text(item.kind.slice(0, 12), MARGIN + 55, y);
      doc.text(item.namespace.slice(0, 16), MARGIN + 75, y);
      doc.text(`${item.blast_radius.toFixed(1)}%`, MARGIN + 105, y);
      const reasonLines: string[] = doc.splitTextToSize(item.reason, CONTENT_WIDTH - 128);
      doc.text(reasonLines[0] ?? '', MARGIN + 128, y);
      y += 5;
    }
    if (report.spof_inventory.items.length > 20) {
      y += 2;
      doc.setFontSize(7);
      doc.setTextColor(...COLOR_MUTED);
      doc.text(
        `... and ${report.spof_inventory.items.length - 20} more items not shown`,
        MARGIN,
        y,
      );
      doc.setTextColor(...COLOR_BLACK);
    }
    y += 5;
  }

  // ── Page 3: Namespace Risk Ranking ───────────────────────────────────

  addPage();
  drawSectionTitle('Namespace Risk Ranking');

  if (report.risk_ranking.namespaces.length === 0) {
    doc.setFontSize(9);
    doc.setFont('helvetica', 'italic');
    doc.text('No namespace risk data available.', MARGIN, y);
    y += 7;
  } else {
    const riskColumns = [
      { label: 'Namespace', x: MARGIN },
      { label: 'Risk Score', x: MARGIN + 55 },
      { label: 'Level', x: MARGIN + 80 },
      { label: 'SPOF Count', x: MARGIN + 105 },
    ];
    drawTableHeader(riskColumns);

    doc.setFontSize(8);
    doc.setFont('helvetica', 'normal');
    const nsItems = report.risk_ranking.namespaces.slice(0, 10);
    for (const ns of nsItems) {
      checkPage(6);
      doc.text(ns.namespace.slice(0, 30), MARGIN, y);
      doc.text(ns.risk_score.toFixed(0), MARGIN + 55, y);

      const levelColor = LEVEL_COLORS[ns.level] ?? COLOR_BLACK;
      doc.setTextColor(...levelColor);
      doc.setFont('helvetica', 'bold');
      doc.text(ns.level.toUpperCase(), MARGIN + 80, y);
      doc.setTextColor(...COLOR_BLACK);
      doc.setFont('helvetica', 'normal');

      doc.text(String(ns.spof_count), MARGIN + 105, y);
      y += 5.5;
    }
    y += 5;
  }

  // ── Page 4: Blast Radius Heatmap ─────────────────────────────────────

  addPage();
  drawSectionTitle('Blast Radius Heatmap');

  if (report.blast_radius_map.top_resources.length === 0) {
    doc.setFontSize(9);
    doc.setFont('helvetica', 'italic');
    doc.text('No blast radius data available.', MARGIN, y);
    y += 7;
  } else {
    const blastColumns = [
      { label: 'Resource', x: MARGIN },
      { label: 'Kind', x: MARGIN + 45 },
      { label: 'Namespace', x: MARGIN + 65 },
      { label: 'Score', x: MARGIN + 95 },
      { label: 'Level', x: MARGIN + 112 },
      { label: 'Affected', x: MARGIN + 138 },
    ];
    drawTableHeader(blastColumns);

    doc.setFontSize(7.5);
    doc.setFont('helvetica', 'normal');
    const blastItems = report.blast_radius_map.top_resources.slice(0, 10);
    for (const res of blastItems) {
      checkPage(6);
      doc.text(res.name.slice(0, 24), MARGIN, y);
      doc.text(res.kind.slice(0, 12), MARGIN + 45, y);
      doc.text(res.namespace.slice(0, 16), MARGIN + 65, y);
      doc.text(res.score.toFixed(0), MARGIN + 95, y);

      const levelColor = LEVEL_COLORS[res.level] ?? COLOR_BLACK;
      doc.setTextColor(...levelColor);
      doc.setFont('helvetica', 'bold');
      doc.text(res.level.toUpperCase(), MARGIN + 112, y);
      doc.setTextColor(...COLOR_BLACK);
      doc.setFont('helvetica', 'normal');

      doc.text(String(res.affected_count), MARGIN + 138, y);
      y += 5.5;
    }
    y += 5;
  }

  // ── Page 5: Recommendations ──────────────────────────────────────────

  addPage();
  drawSectionTitle('Recommendations');

  if (report.recommendations.length === 0) {
    doc.setFontSize(9);
    doc.setFont('helvetica', 'italic');
    doc.text('No recommendations at this time.', MARGIN, y);
  } else {
    for (const rec of report.recommendations) {
      checkPage(20);

      // Priority badge
      const prioColor = LEVEL_COLORS[rec.priority] ?? COLOR_MUTED;
      doc.setFontSize(7);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(255, 255, 255);
      const badgeText = rec.priority.toUpperCase();
      const badgeWidth = doc.getTextWidth(badgeText) + 4;
      doc.setFillColor(...prioColor);
      doc.roundedRect(MARGIN, y - 3, badgeWidth, 4.5, 1, 1, 'F');
      doc.text(badgeText, MARGIN + 2, y);
      doc.setTextColor(...COLOR_BLACK);

      // Title
      doc.setFontSize(9);
      doc.setFont('helvetica', 'bold');
      doc.text(rec.title, MARGIN + badgeWidth + 3, y);
      y += 5;

      // Description
      doc.setFontSize(8);
      doc.setFont('helvetica', 'normal');
      const descLines: string[] = doc.splitTextToSize(rec.description, CONTENT_WIDTH);
      for (const line of descLines) {
        checkPage(5);
        doc.text(line, MARGIN, y);
        y += 4;
      }

      // Impact
      if (rec.impact) {
        doc.setFont('helvetica', 'italic');
        doc.setTextColor(...COLOR_MUTED);
        const impactLines: string[] = doc.splitTextToSize(`Impact: ${rec.impact}`, CONTENT_WIDTH);
        for (const line of impactLines) {
          checkPage(5);
          doc.text(line, MARGIN, y);
          y += 4;
        }
        doc.setTextColor(...COLOR_BLACK);
      }
      y += 4;
    }
  }

  // ── Final footer + save ──────────────────────────────────────────────

  addPageFooter();

  const ts = Date.now();
  const filename = `${report.cluster_name}-resilience-report-${ts}.pdf`;
  doc.save(filename);
}
