/**
 * topologyExport.ts — Enhanced topology export utilities
 *
 * Provides high-quality PNG and SVG export with legend overlay,
 * metadata footer, timestamp, and "Generated by Kubilitics" branding.
 *
 * Uses html-to-image (already a project dependency) for DOM-to-image capture,
 * and the existing adaptive-scaling logic from topology/export/exportTopology.ts.
 */

// ─── Types ───────────────────────────────────────────────────────────────────

export type ExportFormat = 'png' | 'svg';
export type ExportResolution = '1x' | '2x' | '3x';

export interface TopologyExportOptions {
  /** Display title rendered at the top of the export. */
  title: string;
  /** Optional description rendered below the title. */
  description?: string;
  /** Whether to embed the resource/relationship legend. */
  includeLegend: boolean;
  /** Whether to render the generation timestamp. */
  includeTimestamp: boolean;
  /** Output format. */
  format: ExportFormat;
  /** DPI multiplier. */
  resolution: ExportResolution;
  /** Auto-populated cluster name (shown in footer metadata). */
  clusterName?: string;
  /** Active namespace filter (shown in footer metadata). */
  namespaceFilter?: string;
  /** ISO timestamp of generation. */
  generatedAt?: string;
}

// ─── Internal helpers ────────────────────────────────────────────────────────

const RESOLUTION_MAP: Record<ExportResolution, number> = {
  '1x': 1,
  '2x': 2,
  '3x': 3,
};

/** Browser canvas hard-limit safety cap. */
const MAX_CANVAS_PX = 16000;

/**
 * Filter out React Flow UI chrome (minimap, controls, background pattern)
 * so only the topology nodes and edges are captured.
 */
function exportFilter(node: HTMLElement): boolean {
  const cn = node.className?.toString() ?? '';
  if (cn.includes('react-flow__minimap')) return false;
  if (cn.includes('react-flow__controls')) return false;
  if (cn.includes('react-flow__background')) return false;
  // Also exclude any topology panel overlays that shouldn't appear in the export
  if (node.getAttribute?.('data-export-exclude') === 'true') return false;
  return true;
}

/**
 * Compute content bounds by inspecting .react-flow__node elements.
 * Handles both translate(Xpx, Ypx) and translate3d(Xpx, Ypx, Zpx).
 */
function computeNodeBoundsFromDOM(
  viewport: HTMLElement
): { minX: number; minY: number; maxX: number; maxY: number } | null {
  const nodeEls = viewport.querySelectorAll('.react-flow__node');
  if (nodeEls.length === 0) return null;

  let minX = Infinity;
  let minY = Infinity;
  let maxX = -Infinity;
  let maxY = -Infinity;

  const translateRe = /translate(?:3d)?\((-?[\d.]+)px,\s*(-?[\d.]+)px/;

  nodeEls.forEach((el) => {
    const node = el as HTMLElement;
    const style = node.style.transform || '';
    const match = style.match(translateRe);
    if (match) {
      const x = parseFloat(match[1]);
      const y = parseFloat(match[2]);
      minX = Math.min(minX, x);
      minY = Math.min(minY, y);
      maxX = Math.max(maxX, x + node.offsetWidth);
      maxY = Math.max(maxY, y + node.offsetHeight);
    }
  });

  return isFinite(minX) ? { minX, minY, maxX, maxY } : null;
}

/**
 * Compute adaptive scale/pixelRatio so the export stays within browser canvas limits.
 */
function computeExportParams(
  bounds: { minX: number; minY: number; maxX: number; maxY: number },
  resolution: ExportResolution
) {
  const contentW = bounds.maxX - bounds.minX;
  const contentH = bounds.maxY - bounds.minY;
  const padding = Math.max(60, Math.min(120, Math.max(contentW, contentH) * 0.03));

  const TARGET_MAX_DIM = 8000;
  const rawWidth = contentW + padding * 2;
  const rawHeight = contentH + padding * 2;
  const rawMaxDim = Math.max(rawWidth, rawHeight);

  let scale = 1;
  if (rawMaxDim > TARGET_MAX_DIM) {
    scale = TARGET_MAX_DIM / rawMaxDim;
  }

  const captureWidth = Math.ceil(rawWidth * scale);
  const captureHeight = Math.ceil(rawHeight * scale);
  const scaledPadding = padding * scale;

  // Compute pixelRatio: requested resolution, capped by browser canvas limits
  const requestedRatio = RESOLUTION_MAP[resolution];
  const maxDim = Math.max(captureWidth, captureHeight);
  const pixelRatio = Math.max(1, Math.min(requestedRatio, MAX_CANVAS_PX / maxDim));

  return { scale, captureWidth, captureHeight, scaledPadding, pixelRatio };
}

/**
 * Build the metadata/footer text lines for the export.
 */
function buildMetadataLines(options: TopologyExportOptions): string[] {
  const lines: string[] = [];

  if (options.clusterName) {
    lines.push(`Cluster: ${options.clusterName}`);
  }
  if (options.namespaceFilter && options.namespaceFilter !== 'all') {
    lines.push(`Namespace: ${options.namespaceFilter}`);
  }
  if (options.includeTimestamp && options.generatedAt) {
    const d = new Date(options.generatedAt);
    lines.push(`Generated: ${d.toLocaleString()}`);
  }

  lines.push('Generated by Kubilitics');

  return lines;
}

// ─── Legend HTML builder ─────────────────────────────────────────────────────

/**
 * Build a self-contained HTML legend element and inject it into the viewport
 * clone for export capture. Returns the element so the caller can remove it
 * after capture.
 */
function createLegendElement(): HTMLDivElement {
  // Import colors inline to avoid circular deps at module level
  // These are the same NODE_COLORS and RELATIONSHIP_CONFIG from topology-engine
  const nodeCategories: Array<{ label: string; color: string }> = [
    { label: 'Deployment', color: '#FF6B35' },
    { label: 'StatefulSet', color: '#1E88E5' },
    { label: 'DaemonSet', color: '#5E35B1' },
    { label: 'ReplicaSet', color: '#9B59B6' },
    { label: 'Pod', color: '#3498DB' },
    { label: 'Service', color: '#2ECC71' },
    { label: 'Ingress', color: '#26A69A' },
    { label: 'ConfigMap', color: '#FFC107' },
    { label: 'Secret', color: '#E53935' },
    { label: 'PVC', color: '#00ACC1' },
    { label: 'PV', color: '#0097A7' },
    { label: 'Node', color: '#D32F2F' },
    { label: 'Namespace', color: '#7B1FA2' },
    { label: 'Job', color: '#F57C00' },
    { label: 'CronJob', color: '#FF9800' },
  ];

  const relationships: Array<{ label: string; color: string; style: string }> = [
    { label: 'Owns', color: '#64748b', style: 'solid' },
    { label: 'Selects', color: '#a1a1aa', style: 'dashed' },
    { label: 'Exposes', color: '#10b981', style: 'solid' },
    { label: 'Routes', color: '#10b981', style: 'solid' },
    { label: 'Scheduled On', color: '#f97316', style: 'solid' },
    { label: 'Mounts', color: '#14b8a6', style: 'dotted' },
    { label: 'References', color: '#f59e0b', style: 'dashed' },
    { label: 'Contains', color: '#a78bfa', style: 'dashed' },
    { label: 'Permits', color: '#f43f5e', style: 'dashed' },
    { label: 'Manages', color: '#0ea5e9', style: 'solid' },
  ];

  const el = document.createElement('div');
  el.style.cssText = `
    position: absolute; bottom: 0; left: 0; right: 0;
    background: #ffffff; border-top: 1px solid #e2e8f0;
    padding: 12px 16px; font-family: Inter, system-ui, sans-serif;
    z-index: 9999;
  `;

  // Node legend
  let nodesHtml = '<div style="margin-bottom:8px"><div style="font-size:10px;font-weight:700;color:#64748b;text-transform:uppercase;letter-spacing:0.05em;margin-bottom:4px">Resources</div><div style="display:flex;flex-wrap:wrap;gap:8px 12px">';
  for (const cat of nodeCategories) {
    nodesHtml += `<div style="display:flex;align-items:center;gap:4px"><div style="width:10px;height:10px;border-radius:50%;background:${cat.color}"></div><span style="font-size:10px;font-weight:500;color:#475569">${cat.label}</span></div>`;
  }
  nodesHtml += '</div></div>';

  // Edge legend
  let edgesHtml = '<div><div style="font-size:10px;font-weight:700;color:#64748b;text-transform:uppercase;letter-spacing:0.05em;margin-bottom:4px">Relationships</div><div style="display:flex;flex-wrap:wrap;gap:8px 12px">';
  for (const rel of relationships) {
    const dash = rel.style === 'dashed' ? '4 3' : rel.style === 'dotted' ? '2 2' : 'none';
    edgesHtml += `<div style="display:flex;align-items:center;gap:4px"><svg width="18" height="8"><line x1="0" y1="4" x2="14" y2="4" stroke="${rel.color}" stroke-width="2" stroke-dasharray="${dash}"/><polygon points="14,1 18,4 14,7" fill="${rel.color}"/></svg><span style="font-size:10px;font-weight:500;color:#475569">${rel.label}</span></div>`;
  }
  edgesHtml += '</div></div>';

  el.innerHTML = nodesHtml + edgesHtml;
  return el;
}

// ─── Header / footer overlay builders ────────────────────────────────────────

function createHeaderElement(options: TopologyExportOptions): HTMLDivElement {
  const el = document.createElement('div');
  el.style.cssText = `
    position: absolute; top: 0; left: 0; right: 0;
    background: #ffffff; border-bottom: 1px solid #e2e8f0;
    padding: 16px 20px; font-family: Inter, system-ui, sans-serif;
    z-index: 9999;
  `;

  let html = `<div style="font-size:18px;font-weight:700;color:#0f172a;line-height:1.3">${escapeHtml(options.title)}</div>`;
  if (options.description) {
    html += `<div style="font-size:12px;color:#64748b;margin-top:4px;line-height:1.4">${escapeHtml(options.description)}</div>`;
  }

  el.innerHTML = html;
  return el;
}

function createFooterElement(options: TopologyExportOptions): HTMLDivElement {
  const lines = buildMetadataLines(options);
  const el = document.createElement('div');
  el.style.cssText = `
    position: absolute; bottom: 0; left: 0; right: 0;
    background: #f8fafc; border-top: 1px solid #e2e8f0;
    padding: 8px 20px; font-family: Inter, system-ui, sans-serif;
    display: flex; justify-content: space-between; align-items: center;
    z-index: 9999;
  `;

  const metaHtml = lines
    .filter((l) => l !== 'Generated by Kubilitics')
    .map((l) => `<span style="font-size:10px;color:#64748b">${escapeHtml(l)}</span>`)
    .join('<span style="font-size:10px;color:#cbd5e1;margin:0 8px">&bull;</span>');

  el.innerHTML = `
    <div style="display:flex;align-items:center;gap:6px;flex-wrap:wrap">${metaHtml}</div>
    <div style="font-size:10px;color:#94a3b8;font-weight:600">Generated by Kubilitics</div>
  `;

  return el;
}

function escapeHtml(s: string): string {
  return s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
}

// ─── PNG Export ──────────────────────────────────────────────────────────────

/**
 * Export the topology canvas as a high-DPI PNG image.
 *
 * Captures the React Flow viewport using html-to-image, then composites
 * a header (title/description), legend, and metadata footer onto the canvas.
 *
 * @param options - Export configuration from ExportDialog
 * @returns Blob of the PNG image, or null on failure
 */
export async function exportTopologyAsPNG(
  options: TopologyExportOptions
): Promise<Blob | null> {
  const viewport = document.querySelector('.react-flow__viewport') as HTMLElement | null;
  if (!viewport) throw new Error('No React Flow viewport element found');

  const { toPng } = await import('html-to-image');

  const bounds = computeNodeBoundsFromDOM(viewport);
  if (!bounds) throw new Error('No topology nodes found to export');

  const params = computeExportParams(bounds, options.resolution);

  // Step 1: Capture the raw topology as a data URL
  const capturePromise = toPng(viewport, {
    backgroundColor: '#ffffff',
    pixelRatio: params.pixelRatio,
    width: params.captureWidth,
    height: params.captureHeight,
    quality: 1.0,
    style: {
      transform: `translate(${-bounds.minX * params.scale + params.scaledPadding}px, ${-bounds.minY * params.scale + params.scaledPadding}px) scale(${params.scale})`,
      transformOrigin: 'top left',
    },
    filter: exportFilter,
  });

  const timeoutPromise = new Promise<never>((_, reject) =>
    setTimeout(() => reject(new Error('PNG export timed out after 30s')), 30_000)
  );

  const topologyDataUrl = await Promise.race([capturePromise, timeoutPromise]);

  // Step 2: Composite the final image with header, legend, footer
  return compositeImage(topologyDataUrl, options, params);
}

/**
 * Composites the captured topology image with overlays (header, legend, footer)
 * into a single PNG blob.
 */
async function compositeImage(
  topologyDataUrl: string,
  options: TopologyExportOptions,
  params: { captureWidth: number; captureHeight: number; pixelRatio: number }
): Promise<Blob> {
  return new Promise((resolve, reject) => {
    const img = new Image();
    img.onload = () => {
      const pixelRatio = params.pixelRatio;
      const imgW = img.width;
      const imgH = img.height;

      // Calculate overlay heights (in pixel-ratio-scaled coordinates)
      const headerHeight = options.title ? Math.round(56 * pixelRatio) : 0;
      const footerHeight = Math.round(32 * pixelRatio);
      const legendHeight = options.includeLegend ? Math.round(80 * pixelRatio) : 0;

      const totalW = imgW;
      const totalH = imgH + headerHeight + footerHeight + legendHeight;

      const canvas = document.createElement('canvas');
      canvas.width = totalW;
      canvas.height = totalH;
      const ctx = canvas.getContext('2d');
      if (!ctx) {
        reject(new Error('Failed to get canvas 2D context'));
        return;
      }

      // White background
      ctx.fillStyle = '#ffffff';
      ctx.fillRect(0, 0, totalW, totalH);

      // Draw header
      if (headerHeight > 0) {
        ctx.fillStyle = '#ffffff';
        ctx.fillRect(0, 0, totalW, headerHeight);

        // Header border
        ctx.fillStyle = '#e2e8f0';
        ctx.fillRect(0, headerHeight - pixelRatio, totalW, pixelRatio);

        // Title text
        ctx.fillStyle = '#0f172a';
        ctx.font = `bold ${Math.round(16 * pixelRatio)}px Inter, system-ui, sans-serif`;
        ctx.fillText(options.title, Math.round(20 * pixelRatio), Math.round(28 * pixelRatio));

        // Description text
        if (options.description) {
          ctx.fillStyle = '#64748b';
          ctx.font = `${Math.round(11 * pixelRatio)}px Inter, system-ui, sans-serif`;
          ctx.fillText(options.description, Math.round(20 * pixelRatio), Math.round(44 * pixelRatio));
        }
      }

      // Draw topology image
      ctx.drawImage(img, 0, headerHeight);

      // Draw legend area
      if (legendHeight > 0) {
        const legendY = headerHeight + imgH;
        ctx.fillStyle = '#ffffff';
        ctx.fillRect(0, legendY, totalW, legendHeight);
        ctx.fillStyle = '#e2e8f0';
        ctx.fillRect(0, legendY, totalW, pixelRatio);

        // Resource circles
        const nodeCats = [
          { label: 'Deployment', color: '#FF6B35' },
          { label: 'Pod', color: '#3498DB' },
          { label: 'Service', color: '#2ECC71' },
          { label: 'Ingress', color: '#26A69A' },
          { label: 'ConfigMap', color: '#FFC107' },
          { label: 'Secret', color: '#E53935' },
          { label: 'Node', color: '#D32F2F' },
          { label: 'PVC', color: '#00ACC1' },
          { label: 'Namespace', color: '#7B1FA2' },
        ];

        const fontSize = Math.round(9 * pixelRatio);
        const dotSize = Math.round(4 * pixelRatio);
        ctx.font = `500 ${fontSize}px Inter, system-ui, sans-serif`;

        let xOff = Math.round(16 * pixelRatio);
        const yBase = legendY + Math.round(14 * pixelRatio);

        // Section label
        ctx.fillStyle = '#64748b';
        ctx.font = `700 ${fontSize}px Inter, system-ui, sans-serif`;
        ctx.fillText('Resources:', xOff, yBase);
        xOff += ctx.measureText('Resources:').width + Math.round(8 * pixelRatio);
        ctx.font = `500 ${fontSize}px Inter, system-ui, sans-serif`;

        for (const cat of nodeCats) {
          ctx.fillStyle = cat.color;
          ctx.beginPath();
          ctx.arc(xOff + dotSize, yBase - dotSize, dotSize, 0, Math.PI * 2);
          ctx.fill();

          ctx.fillStyle = '#475569';
          ctx.fillText(cat.label, xOff + dotSize * 3, yBase);
          xOff += dotSize * 3 + ctx.measureText(cat.label).width + Math.round(10 * pixelRatio);
        }

        // Relationships row
        const relTypes = [
          { label: 'Owns', color: '#64748b' },
          { label: 'Selects', color: '#a1a1aa' },
          { label: 'Routes', color: '#10b981' },
          { label: 'Mounts', color: '#14b8a6' },
          { label: 'References', color: '#f59e0b' },
          { label: 'Manages', color: '#0ea5e9' },
        ];

        let xOff2 = Math.round(16 * pixelRatio);
        const yBase2 = legendY + Math.round(34 * pixelRatio);

        ctx.fillStyle = '#64748b';
        ctx.font = `700 ${fontSize}px Inter, system-ui, sans-serif`;
        ctx.fillText('Relationships:', xOff2, yBase2);
        xOff2 += ctx.measureText('Relationships:').width + Math.round(8 * pixelRatio);
        ctx.font = `500 ${fontSize}px Inter, system-ui, sans-serif`;

        for (const rel of relTypes) {
          // Draw short line
          ctx.strokeStyle = rel.color;
          ctx.lineWidth = Math.round(1.5 * pixelRatio);
          ctx.beginPath();
          ctx.moveTo(xOff2, yBase2 - Math.round(2 * pixelRatio));
          ctx.lineTo(xOff2 + Math.round(12 * pixelRatio), yBase2 - Math.round(2 * pixelRatio));
          ctx.stroke();

          // Arrow head
          const ax = xOff2 + Math.round(12 * pixelRatio);
          const ay = yBase2 - Math.round(2 * pixelRatio);
          ctx.fillStyle = rel.color;
          ctx.beginPath();
          ctx.moveTo(ax, ay - Math.round(3 * pixelRatio));
          ctx.lineTo(ax + Math.round(4 * pixelRatio), ay);
          ctx.lineTo(ax, ay + Math.round(3 * pixelRatio));
          ctx.closePath();
          ctx.fill();

          ctx.fillStyle = '#475569';
          ctx.fillText(rel.label, xOff2 + Math.round(18 * pixelRatio), yBase2);
          xOff2 += Math.round(18 * pixelRatio) + ctx.measureText(rel.label).width + Math.round(10 * pixelRatio);
        }
      }

      // Draw footer
      const footerY = totalH - footerHeight;
      ctx.fillStyle = '#f8fafc';
      ctx.fillRect(0, footerY, totalW, footerHeight);
      ctx.fillStyle = '#e2e8f0';
      ctx.fillRect(0, footerY, totalW, pixelRatio);

      const footerFontSize = Math.round(9 * pixelRatio);
      ctx.font = `500 ${footerFontSize}px Inter, system-ui, sans-serif`;

      // Left side: metadata
      const metaLines = buildMetadataLines(options).filter((l) => l !== 'Generated by Kubilitics');
      ctx.fillStyle = '#64748b';
      ctx.fillText(
        metaLines.join('  |  '),
        Math.round(20 * pixelRatio),
        footerY + Math.round(20 * pixelRatio)
      );

      // Right side: branding
      ctx.fillStyle = '#94a3b8';
      ctx.font = `600 ${footerFontSize}px Inter, system-ui, sans-serif`;
      const brandText = 'Generated by Kubilitics';
      const brandWidth = ctx.measureText(brandText).width;
      ctx.fillText(
        brandText,
        totalW - brandWidth - Math.round(20 * pixelRatio),
        footerY + Math.round(20 * pixelRatio)
      );

      canvas.toBlob(
        (blob) => {
          if (blob) resolve(blob);
          else reject(new Error('Canvas toBlob returned null'));
        },
        'image/png',
        1.0
      );
    };

    img.onerror = () => reject(new Error('Failed to load captured topology image'));
    img.src = topologyDataUrl;
  });
}

// ─── SVG Export ──────────────────────────────────────────────────────────────

/**
 * Export the topology canvas as an SVG image.
 *
 * Captures the React Flow viewport using html-to-image's toSvg, then injects
 * title, legend, and metadata as SVG text elements.
 *
 * @param options - Export configuration from ExportDialog
 * @returns Blob of the SVG image, or null on failure
 */
export async function exportTopologyAsSVG(
  options: TopologyExportOptions
): Promise<Blob | null> {
  const viewport = document.querySelector('.react-flow__viewport') as HTMLElement | null;
  if (!viewport) throw new Error('No React Flow viewport element found');

  const { toSvg } = await import('html-to-image');

  const bounds = computeNodeBoundsFromDOM(viewport);
  if (!bounds) throw new Error('No topology nodes found to export');

  const params = computeExportParams(bounds, options.resolution);

  const capturePromise = toSvg(viewport, {
    backgroundColor: '#ffffff',
    width: params.captureWidth,
    height: params.captureHeight,
    style: {
      transform: `translate(${-bounds.minX * params.scale + params.scaledPadding}px, ${-bounds.minY * params.scale + params.scaledPadding}px) scale(${params.scale})`,
      transformOrigin: 'top left',
    },
    filter: exportFilter,
  });

  const timeoutPromise = new Promise<never>((_, reject) =>
    setTimeout(() => reject(new Error('SVG export timed out after 30s')), 30_000)
  );

  const svgDataUrl = await Promise.race([capturePromise, timeoutPromise]);

  // html-to-image returns a data URL — extract the SVG XML
  const svgXml = decodeURIComponent(svgDataUrl.split(',')[1] ?? '');
  if (!svgXml) throw new Error('Failed to decode SVG data');

  // Parse and augment the SVG with title, legend, footer
  const augmentedSvg = augmentSvg(svgXml, options);

  return new Blob([augmentedSvg], { type: 'image/svg+xml' });
}

/**
 * Augment a captured SVG string with title, legend, and footer metadata.
 */
function augmentSvg(svgXml: string, options: TopologyExportOptions): string {
  const parser = new DOMParser();
  const doc = parser.parseFromString(svgXml, 'image/svg+xml');
  const svg = doc.documentElement;

  const width = parseFloat(svg.getAttribute('width') || '800');
  const height = parseFloat(svg.getAttribute('height') || '600');

  // Calculate overlay sizes
  const headerH = options.title ? 56 : 0;
  const footerH = 32;
  const legendH = options.includeLegend ? 50 : 0;
  const newHeight = height + headerH + footerH + legendH;

  svg.setAttribute('height', String(newHeight));
  svg.setAttribute('viewBox', `0 0 ${width} ${newHeight}`);

  // Wrap existing content in a group translated down by headerH
  const existingContent = Array.from(svg.childNodes);
  const contentGroup = doc.createElementNS('http://www.w3.org/2000/svg', 'g');
  contentGroup.setAttribute('transform', `translate(0, ${headerH})`);
  existingContent.forEach((child) => contentGroup.appendChild(child));
  svg.appendChild(contentGroup);

  // Header
  if (headerH > 0) {
    const headerGroup = doc.createElementNS('http://www.w3.org/2000/svg', 'g');

    // Background
    const headerBg = doc.createElementNS('http://www.w3.org/2000/svg', 'rect');
    headerBg.setAttribute('x', '0');
    headerBg.setAttribute('y', '0');
    headerBg.setAttribute('width', String(width));
    headerBg.setAttribute('height', String(headerH));
    headerBg.setAttribute('fill', '#ffffff');
    headerGroup.appendChild(headerBg);

    // Border line
    const headerLine = doc.createElementNS('http://www.w3.org/2000/svg', 'line');
    headerLine.setAttribute('x1', '0');
    headerLine.setAttribute('y1', String(headerH));
    headerLine.setAttribute('x2', String(width));
    headerLine.setAttribute('y2', String(headerH));
    headerLine.setAttribute('stroke', '#e2e8f0');
    headerLine.setAttribute('stroke-width', '1');
    headerGroup.appendChild(headerLine);

    // Title
    const titleText = doc.createElementNS('http://www.w3.org/2000/svg', 'text');
    titleText.setAttribute('x', '20');
    titleText.setAttribute('y', '28');
    titleText.setAttribute('font-family', 'Inter, system-ui, sans-serif');
    titleText.setAttribute('font-size', '16');
    titleText.setAttribute('font-weight', '700');
    titleText.setAttribute('fill', '#0f172a');
    titleText.textContent = options.title;
    headerGroup.appendChild(titleText);

    // Description
    if (options.description) {
      const descText = doc.createElementNS('http://www.w3.org/2000/svg', 'text');
      descText.setAttribute('x', '20');
      descText.setAttribute('y', '46');
      descText.setAttribute('font-family', 'Inter, system-ui, sans-serif');
      descText.setAttribute('font-size', '11');
      descText.setAttribute('fill', '#64748b');
      descText.textContent = options.description;
      headerGroup.appendChild(descText);
    }

    svg.appendChild(headerGroup);
  }

  // Footer
  const footerY = newHeight - footerH;
  const footerGroup = doc.createElementNS('http://www.w3.org/2000/svg', 'g');

  const footerBg = doc.createElementNS('http://www.w3.org/2000/svg', 'rect');
  footerBg.setAttribute('x', '0');
  footerBg.setAttribute('y', String(footerY));
  footerBg.setAttribute('width', String(width));
  footerBg.setAttribute('height', String(footerH));
  footerBg.setAttribute('fill', '#f8fafc');
  footerGroup.appendChild(footerBg);

  const footerLine = doc.createElementNS('http://www.w3.org/2000/svg', 'line');
  footerLine.setAttribute('x1', '0');
  footerLine.setAttribute('y1', String(footerY));
  footerLine.setAttribute('x2', String(width));
  footerLine.setAttribute('y2', String(footerY));
  footerLine.setAttribute('stroke', '#e2e8f0');
  footerLine.setAttribute('stroke-width', '1');
  footerGroup.appendChild(footerLine);

  // Metadata text (left)
  const metaLines = buildMetadataLines(options).filter((l) => l !== 'Generated by Kubilitics');
  const metaText = doc.createElementNS('http://www.w3.org/2000/svg', 'text');
  metaText.setAttribute('x', '20');
  metaText.setAttribute('y', String(footerY + 20));
  metaText.setAttribute('font-family', 'Inter, system-ui, sans-serif');
  metaText.setAttribute('font-size', '9');
  metaText.setAttribute('fill', '#64748b');
  metaText.textContent = metaLines.join('  |  ');
  footerGroup.appendChild(metaText);

  // Branding (right)
  const brandText = doc.createElementNS('http://www.w3.org/2000/svg', 'text');
  brandText.setAttribute('x', String(width - 20));
  brandText.setAttribute('y', String(footerY + 20));
  brandText.setAttribute('font-family', 'Inter, system-ui, sans-serif');
  brandText.setAttribute('font-size', '9');
  brandText.setAttribute('font-weight', '600');
  brandText.setAttribute('fill', '#94a3b8');
  brandText.setAttribute('text-anchor', 'end');
  brandText.textContent = 'Generated by Kubilitics';
  footerGroup.appendChild(brandText);

  svg.appendChild(footerGroup);

  // Legend (between topology content and footer)
  if (options.includeLegend && legendH > 0) {
    const legendY = headerH + height;
    const legendGroup = doc.createElementNS('http://www.w3.org/2000/svg', 'g');

    const legendBg = doc.createElementNS('http://www.w3.org/2000/svg', 'rect');
    legendBg.setAttribute('x', '0');
    legendBg.setAttribute('y', String(legendY));
    legendBg.setAttribute('width', String(width));
    legendBg.setAttribute('height', String(legendH));
    legendBg.setAttribute('fill', '#ffffff');
    legendGroup.appendChild(legendBg);

    const legendBorder = doc.createElementNS('http://www.w3.org/2000/svg', 'line');
    legendBorder.setAttribute('x1', '0');
    legendBorder.setAttribute('y1', String(legendY));
    legendBorder.setAttribute('x2', String(width));
    legendBorder.setAttribute('y2', String(legendY));
    legendBorder.setAttribute('stroke', '#e2e8f0');
    legendBorder.setAttribute('stroke-width', '1');
    legendGroup.appendChild(legendBorder);

    // Compact legend items
    const items = [
      { label: 'Deployment', color: '#FF6B35' },
      { label: 'Pod', color: '#3498DB' },
      { label: 'Service', color: '#2ECC71' },
      { label: 'Ingress', color: '#26A69A' },
      { label: 'ConfigMap', color: '#FFC107' },
      { label: 'Secret', color: '#E53935' },
      { label: 'Node', color: '#D32F2F' },
      { label: 'Namespace', color: '#7B1FA2' },
    ];

    let xOff = 16;
    const yOff = legendY + 18;

    // Section label
    const sectionLabel = doc.createElementNS('http://www.w3.org/2000/svg', 'text');
    sectionLabel.setAttribute('x', String(xOff));
    sectionLabel.setAttribute('y', String(yOff));
    sectionLabel.setAttribute('font-family', 'Inter, system-ui, sans-serif');
    sectionLabel.setAttribute('font-size', '9');
    sectionLabel.setAttribute('font-weight', '700');
    sectionLabel.setAttribute('fill', '#64748b');
    sectionLabel.textContent = 'Resources:';
    legendGroup.appendChild(sectionLabel);
    xOff += 60;

    for (const item of items) {
      const circle = doc.createElementNS('http://www.w3.org/2000/svg', 'circle');
      circle.setAttribute('cx', String(xOff + 4));
      circle.setAttribute('cy', String(yOff - 3));
      circle.setAttribute('r', '4');
      circle.setAttribute('fill', item.color);
      legendGroup.appendChild(circle);

      const text = doc.createElementNS('http://www.w3.org/2000/svg', 'text');
      text.setAttribute('x', String(xOff + 12));
      text.setAttribute('y', String(yOff));
      text.setAttribute('font-family', 'Inter, system-ui, sans-serif');
      text.setAttribute('font-size', '9');
      text.setAttribute('fill', '#475569');
      text.textContent = item.label;
      legendGroup.appendChild(text);

      // Approximate character width for positioning
      xOff += 12 + item.label.length * 5.5 + 10;
    }

    svg.appendChild(legendGroup);
  }

  const serializer = new XMLSerializer();
  return serializer.serializeToString(svg);
}
