apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: pod-security.kubilitics-demo
  labels:
    app.kubernetes.io/part-of: kubilitics-demo
webhooks:
  - name: pod-security.kubilitics.com
    admissionReviewVersions: ["v1"]
    sideEffects: None
    failurePolicy: Ignore
    clientConfig:
      service:
        namespace: kubilitics-demo
        name: api-server
        path: /validate-security
        port: 80
      caBundle: "Cg=="
    rules:
      - apiGroups: [""]
        apiVersions: ["v1"]
        operations: ["CREATE","UPDATE"]
        resources: ["pods"]
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: network-policy-guard.kubilitics-demo
  labels:
    app.kubernetes.io/part-of: kubilitics-demo
webhooks:
  - name: network-policy-guard.kubilitics.com
    admissionReviewVersions: ["v1"]
    sideEffects: None
    failurePolicy: Ignore
    clientConfig:
      service:
        namespace: kubilitics-demo
        name: api-server
        path: /validate-network
        port: 80
      caBundle: "Cg=="
    rules:
      - apiGroups: [""]
        apiVersions: ["v1"]
        operations: ["CREATE"]
        resources: ["namespaces"]
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: quota-enforcer.kubilitics-demo
  labels:
    app.kubernetes.io/part-of: kubilitics-demo
webhooks:
  - name: quota-enforcer.kubilitics.com
    admissionReviewVersions: ["v1"]
    sideEffects: None
    failurePolicy: Ignore
    clientConfig:
      service:
        namespace: kubilitics-demo
        name: api-server
        path: /validate-quota
        port: 80
      caBundle: "Cg=="
    rules:
      - apiGroups: [""]
        apiVersions: ["v1"]
        operations: ["CREATE","UPDATE"]
        resources: ["resourcequotas"]

