apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kubilitics-otel.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kubilitics-otel.labels" . | nindent 4 }}
{{- with .Values.image.imagePullSecrets }}
imagePullSecrets:
  {{- toYaml . | nindent 2 }}
{{- end }}
