// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: v1/agent_runtime.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AgentRuntimeService_Chat_FullMethodName         = "/kubilitics.ai.v1.AgentRuntimeService/Chat"
	AgentRuntimeService_RunAgent_FullMethodName     = "/kubilitics.ai.v1.AgentRuntimeService/RunAgent"
	AgentRuntimeService_CancelTurn_FullMethodName   = "/kubilitics.ai.v1.AgentRuntimeService/CancelTurn"
	AgentRuntimeService_Capabilities_FullMethodName = "/kubilitics.ai.v1.AgentRuntimeService/Capabilities"
)

// AgentRuntimeServiceClient is the client API for AgentRuntimeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AgentRuntimeServiceClient interface {
	Chat(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ChatRequest, AIEvent], error)
	RunAgent(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AgentRequest, AIEvent], error)
	CancelTurn(ctx context.Context, in *CancelRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	Capabilities(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*CapabilitiesResponse, error)
}

type agentRuntimeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentRuntimeServiceClient(cc grpc.ClientConnInterface) AgentRuntimeServiceClient {
	return &agentRuntimeServiceClient{cc}
}

func (c *agentRuntimeServiceClient) Chat(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ChatRequest, AIEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AgentRuntimeService_ServiceDesc.Streams[0], AgentRuntimeService_Chat_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ChatRequest, AIEvent]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentRuntimeService_ChatClient = grpc.BidiStreamingClient[ChatRequest, AIEvent]

func (c *agentRuntimeServiceClient) RunAgent(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AgentRequest, AIEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AgentRuntimeService_ServiceDesc.Streams[1], AgentRuntimeService_RunAgent_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[AgentRequest, AIEvent]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentRuntimeService_RunAgentClient = grpc.BidiStreamingClient[AgentRequest, AIEvent]

func (c *agentRuntimeServiceClient) CancelTurn(ctx context.Context, in *CancelRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, AgentRuntimeService_CancelTurn_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentRuntimeServiceClient) Capabilities(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*CapabilitiesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CapabilitiesResponse)
	err := c.cc.Invoke(ctx, AgentRuntimeService_Capabilities_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AgentRuntimeServiceServer is the server API for AgentRuntimeService service.
// All implementations must embed UnimplementedAgentRuntimeServiceServer
// for forward compatibility.
type AgentRuntimeServiceServer interface {
	Chat(grpc.BidiStreamingServer[ChatRequest, AIEvent]) error
	RunAgent(grpc.BidiStreamingServer[AgentRequest, AIEvent]) error
	CancelTurn(context.Context, *CancelRequest) (*emptypb.Empty, error)
	Capabilities(context.Context, *emptypb.Empty) (*CapabilitiesResponse, error)
	mustEmbedUnimplementedAgentRuntimeServiceServer()
}

// UnimplementedAgentRuntimeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgentRuntimeServiceServer struct{}

func (UnimplementedAgentRuntimeServiceServer) Chat(grpc.BidiStreamingServer[ChatRequest, AIEvent]) error {
	return status.Errorf(codes.Unimplemented, "method Chat not implemented")
}
func (UnimplementedAgentRuntimeServiceServer) RunAgent(grpc.BidiStreamingServer[AgentRequest, AIEvent]) error {
	return status.Errorf(codes.Unimplemented, "method RunAgent not implemented")
}
func (UnimplementedAgentRuntimeServiceServer) CancelTurn(context.Context, *CancelRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CancelTurn not implemented")
}
func (UnimplementedAgentRuntimeServiceServer) Capabilities(context.Context, *emptypb.Empty) (*CapabilitiesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Capabilities not implemented")
}
func (UnimplementedAgentRuntimeServiceServer) mustEmbedUnimplementedAgentRuntimeServiceServer() {}
func (UnimplementedAgentRuntimeServiceServer) testEmbeddedByValue()                             {}

// UnsafeAgentRuntimeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentRuntimeServiceServer will
// result in compilation errors.
type UnsafeAgentRuntimeServiceServer interface {
	mustEmbedUnimplementedAgentRuntimeServiceServer()
}

func RegisterAgentRuntimeServiceServer(s grpc.ServiceRegistrar, srv AgentRuntimeServiceServer) {
	// If the following call pancis, it indicates UnimplementedAgentRuntimeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AgentRuntimeService_ServiceDesc, srv)
}

func _AgentRuntimeService_Chat_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AgentRuntimeServiceServer).Chat(&grpc.GenericServerStream[ChatRequest, AIEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentRuntimeService_ChatServer = grpc.BidiStreamingServer[ChatRequest, AIEvent]

func _AgentRuntimeService_RunAgent_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AgentRuntimeServiceServer).RunAgent(&grpc.GenericServerStream[AgentRequest, AIEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentRuntimeService_RunAgentServer = grpc.BidiStreamingServer[AgentRequest, AIEvent]

func _AgentRuntimeService_CancelTurn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentRuntimeServiceServer).CancelTurn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentRuntimeService_CancelTurn_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentRuntimeServiceServer).CancelTurn(ctx, req.(*CancelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentRuntimeService_Capabilities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentRuntimeServiceServer).Capabilities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentRuntimeService_Capabilities_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentRuntimeServiceServer).Capabilities(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// AgentRuntimeService_ServiceDesc is the grpc.ServiceDesc for AgentRuntimeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentRuntimeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "kubilitics.ai.v1.AgentRuntimeService",
	HandlerType: (*AgentRuntimeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CancelTurn",
			Handler:    _AgentRuntimeService_CancelTurn_Handler,
		},
		{
			MethodName: "Capabilities",
			Handler:    _AgentRuntimeService_Capabilities_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Chat",
			Handler:       _AgentRuntimeService_Chat_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "RunAgent",
			Handler:       _AgentRuntimeService_RunAgent_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "v1/agent_runtime.proto",
}
