apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshotClass
metadata:
  name: fast-ssd-snap
  labels:
    app.kubernetes.io/part-of: kubilitics-demo
driver: csi.fast-ssd.example.com
deletionPolicy: Delete
---
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshotClass
metadata:
  name: standard-hdd-snap
  labels:
    app.kubernetes.io/part-of: kubilitics-demo
driver: csi.standard-hdd.example.com
deletionPolicy: Retain
---
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshotClass
metadata:
  name: replicated-nvme-snap
  labels:
    app.kubernetes.io/part-of: kubilitics-demo
driver: csi.replicated-nvme.example.com
deletionPolicy: Retain

