apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: kubilitics-critical
  labels:
    app.kubernetes.io/part-of: kubilitics-demo
value: 1000000
globalDefault: false
description: "Critical control-plane workloads"
---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: kubilitics-high
  labels:
    app.kubernetes.io/part-of: kubilitics-demo
value: 900000
globalDefault: false
description: "High priority workloads"
---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: kubilitics-low
  labels:
    app.kubernetes.io/part-of: kubilitics-demo
value: 1000
globalDefault: true
description: "Default low-priority workloads"
---
apiVersion: coordination.k8s.io/v1
kind: Lease
metadata:
  name: api-leader
  namespace: kubilitics-demo
  labels:
    app.kubernetes.io/part-of: kubilitics-demo
spec:
  holderIdentity: api-server-0
  leaseDurationSeconds: 15
---
apiVersion: coordination.k8s.io/v1
kind: Lease
metadata:
  name: kafka-controller
  namespace: analytics-staging
  labels:
    app.kubernetes.io/part-of: kubilitics-demo
spec:
  holderIdentity: kafka-broker-0
  leaseDurationSeconds: 15
---
apiVersion: coordination.k8s.io/v1
kind: Lease
metadata:
  name: payments-lock
  namespace: payments-prod
  labels:
    app.kubernetes.io/part-of: kubilitics-demo
spec:
  holderIdentity: etcd-cluster-0
  leaseDurationSeconds: 30
---
apiVersion: v1
kind: PodTemplate
metadata:
  name: debug-shell
  namespace: kubilitics-demo
  labels:
    app.kubernetes.io/part-of: kubilitics-demo
template:
  metadata:
    labels:
      app: debug-shell
  spec:
    containers:
      - name: shell
        image: busybox:1.36
        command: ["sh","-c","sleep 3600"]
---
apiVersion: v1
kind: PodTemplate
metadata:
  name: analytics-worker-template
  namespace: analytics-staging
  labels:
    app.kubernetes.io/part-of: kubilitics-demo
template:
  metadata:
    labels:
      app: analytics-worker
  spec:
    containers:
      - name: worker
        image: busybox:1.36
        command: ["sh","-c","echo 'processing batch'; sleep 60"]
---
apiVersion: v1
kind: PodTemplate
metadata:
  name: payment-worker-template
  namespace: payments-prod
  labels:
    app.kubernetes.io/part-of: kubilitics-demo
template:
  metadata:
    labels:
      app: payment-worker
  spec:
    containers:
      - name: worker
        image: busybox:1.36
        command: ["sh","-c","echo 'processing payments'; sleep 60"]

