#!/usr/bin/env bash
# publish-homebrew-formula.sh — compute DMG SHA256s from a GitHub release
# and open a PR against the Homebrew tap with the updated formula.
#
# Usage:
#   ./scripts/publish-homebrew-formula.sh v1.1.0
#
# Requirements:
#   - gh (authenticated against both vellankikoti/kubilitics and
#     vellankikoti/homebrew-kubilitics)
#   - local clone of the tap at $TAP_PATH (default: ../homebrew-kubilitics)

set -euo pipefail

TAG="${1:?usage: $0 vX.Y.Z}"
VERSION="${TAG#v}"
TAP_PATH="${TAP_PATH:-../homebrew-kubilitics}"

if [ ! -d "$TAP_PATH" ]; then
  echo "ERROR: Homebrew tap clone not found at $TAP_PATH" >&2
  echo "       Clone https://github.com/vellankikoti/homebrew-kubilitics first" >&2
  exit 1
fi

# Fetch the DMG checksums from the release's checksums.txt asset.
echo "Downloading checksums.txt for $TAG"
TMP=$(mktemp -d)
trap 'rm -rf "$TMP"' EXIT
gh release download "$TAG" --repo vellankikoti/kubilitics --pattern "checksums.txt" --dir "$TMP"

ARM_SHA=$(awk "/Kubilitics_${VERSION}_aarch64\.dmg$/ {print \$1}" "$TMP/checksums.txt")
X86_SHA=$(awk "/Kubilitics_${VERSION}_x64\.dmg$/ {print \$1}" "$TMP/checksums.txt")

if [ -z "$ARM_SHA" ] || [ -z "$X86_SHA" ]; then
  echo "ERROR: could not find DMG entries in checksums.txt:" >&2
  cat "$TMP/checksums.txt" >&2
  exit 1
fi

echo "arm64 sha: $ARM_SHA"
echo "x86_64 sha: $X86_SHA"

# Copy our canonical formula into the tap with the SHAs substituted.
cp deploy/homebrew/kubilitics.rb "$TAP_PATH/Casks/kubilitics.rb"
sed -i.bak "s/^  version \"[^\"]*\"/  version \"$VERSION\"/" "$TAP_PATH/Casks/kubilitics.rb"
sed -i.bak "s/REPLACE_WITH_AARCH64_DMG_SHA256/$ARM_SHA/" "$TAP_PATH/Casks/kubilitics.rb"
sed -i.bak "s/REPLACE_WITH_X86_64_DMG_SHA256/$X86_SHA/" "$TAP_PATH/Casks/kubilitics.rb"
rm -f "$TAP_PATH/Casks/kubilitics.rb.bak"

cd "$TAP_PATH"
BRANCH="release/$TAG"
git checkout -B "$BRANCH"
git add Casks/kubilitics.rb
git commit -m "release: Kubilitics $TAG"
git push -u origin "$BRANCH"

gh pr create \
  --repo vellankikoti/homebrew-kubilitics \
  --title "release: Kubilitics $TAG" \
  --body "Auto-generated by publish-homebrew-formula.sh from checksums.txt." \
  --base main --head "$BRANCH"

echo "✓ PR opened on vellankikoti/homebrew-kubilitics for $TAG"
