/**
 * PDF export for topology visualization.
 * Generates SVG first, then converts to PDF using jspdf.
 */
export async function exportTopologyPDF(
  clusterId?: string,
  viewMode?: string,
  selectedNamespaces?: Set<string>
): Promise<void> {
  const viewport = document.querySelector(".react-flow__viewport");
  if (!viewport) {
    console.warn("No React Flow viewport found for PDF export");
    return;
  }

  // Dynamically import dependencies
  const [{ toSvg }, { jsPDF }] = await Promise.all([
    import("html-to-image"),
    import("jspdf"),
  ]);

  // Generate SVG data URL
  const svgDataUrl = await toSvg(viewport as HTMLElement, {
    backgroundColor: "#ffffff",
    style: {
      transform: "none",
    },
  });

  // Create PDF
  const pdf = new jsPDF({
    orientation: "landscape",
    unit: "px",
    format: [1920, 1080],
  });

  // Add header
  const dateStr = new Date().toLocaleDateString();
  const title = `Kubilitics Topology — ${clusterId ?? "cluster"} — ${dateStr}`;
  pdf.setFontSize(14);
  pdf.text(title, 40, 30);

  // Add image
  const img = new Image();
  img.src = svgDataUrl;
  await new Promise<void>((resolve) => {
    img.onload = () => {
      const maxW = 1840;
      const maxH = 1000;
      const scale = Math.min(maxW / img.width, maxH / img.height, 1);
      const w = img.width * scale;
      const h = img.height * scale;
      const x = (1920 - w) / 2;
      pdf.addImage(svgDataUrl, "SVG", x, 50, w, h);
      resolve();
    };
    img.onerror = () => resolve();
  });

  // Add footer
  pdf.setFontSize(8);
  pdf.text(`Generated by Kubilitics | ${viewMode ?? "namespace"} view | ${dateStr}`, 40, 1060);
  pdf.text("1", 1880, 1060, { align: "right" });

  // Download
  const nsPart = selectedNamespaces && selectedNamespaces.size > 0
    ? `-${Array.from(selectedNamespaces).slice(0, 3).join("-")}`
    : "";
  const ts = Date.now();
  const filename = `${clusterId ?? "cluster"}${nsPart}-${viewMode ?? "namespace"}-${ts}.pdf`;
  pdf.save(filename);
}
