/**
 * PDF export for topology visualization.
 * Uses the same adaptive scaling as PNG/SVG, then embeds in a
 * dynamically-sized PDF page.
 */
import { EXPORT } from "../constants/designTokens";
import type { ExportBounds } from "./exportTopology";

export async function exportTopologyPDF(
  clusterName?: string,
  viewMode?: string,
  selectedNamespaces?: Set<string>,
  precomputedBounds?: ExportBounds
): Promise<void> {
  const viewport = document.querySelector(".react-flow__viewport") as HTMLElement | null;
  if (!viewport) {
    console.warn("No React Flow viewport found for PDF export");
    return;
  }

  // Dynamically import dependencies
  const [{ toPng }, { jsPDF }] = await Promise.all([
    import("html-to-image"),
    import("jspdf"),
  ]);

  // Compute node bounds — prefer pre-computed from React Flow state
  let minX: number, minY: number, maxX: number, maxY: number;

  if (precomputedBounds) {
    ({ minX, minY, maxX, maxY } = precomputedBounds);
  } else {
    // DOM fallback with robust translate/translate3d regex
    const nodeEls = viewport.querySelectorAll(".react-flow__node");
    if (nodeEls.length === 0) return;

    minX = Infinity; minY = Infinity; maxX = -Infinity; maxY = -Infinity;
    const translateRe = /translate(?:3d)?\((-?[\d.]+)px,\s*(-?[\d.]+)px/;
    nodeEls.forEach((el) => {
      const node = el as HTMLElement;
      const style = node.style.transform || "";
      const match = style.match(translateRe);
      if (match) {
        const x = parseFloat(match[1]);
        const y = parseFloat(match[2]);
        minX = Math.min(minX, x);
        minY = Math.min(minY, y);
        maxX = Math.max(maxX, x + node.offsetWidth);
        maxY = Math.max(maxY, y + node.offsetHeight);
      }
    });

    if (!isFinite(minX)) return;
  }

  const contentW = maxX - minX;
  const contentH = maxY - minY;
  const padding = EXPORT.dynamicPadding(contentW, contentH);

  // Adaptive scaling: same logic as PNG export but target max 6000px for PDF
  const TARGET_MAX = 6000;
  const rawWidth = contentW + padding * 2;
  const rawHeight = contentH + padding * 2;
  const rawMaxDim = Math.max(rawWidth, rawHeight);
  const scale = rawMaxDim > TARGET_MAX ? TARGET_MAX / rawMaxDim : 1;

  const captureWidth = Math.ceil(rawWidth * scale);
  const captureHeight = Math.ceil(rawHeight * scale);
  const scaledPadding = padding * scale;

  // Capture
  const pngDataUrl = await toPng(viewport, {
    backgroundColor: EXPORT.backgroundColor,
    pixelRatio: 1.5, // Good quality for PDF without hitting canvas limits
    width: captureWidth,
    height: captureHeight,
    quality: 1.0,
    style: {
      transform: `translate(${-minX * scale + scaledPadding}px, ${-minY * scale + scaledPadding}px) scale(${scale})`,
      transformOrigin: "top left",
    },
    filter: (node: HTMLElement) => {
      const cn = node.className?.toString() ?? "";
      if (cn.includes("react-flow__minimap")) return false;
      if (cn.includes("react-flow__controls")) return false;
      if (cn.includes("react-flow__background")) return false;
      return true;
    },
  });

  // Dynamic page size — fit content with margin for header/footer
  const headerHeight = 50;
  const footerHeight = 30;
  const pageWidth = captureWidth + 80;
  const pageHeight = captureHeight + headerHeight + footerHeight + 40;

  const pdf = new jsPDF({
    orientation: pageWidth > pageHeight ? "landscape" : "portrait",
    unit: "px",
    format: [pageWidth, pageHeight],
  });

  // Header
  const dateStr = new Date().toLocaleDateString();
  const title = `Kubilitics Topology — ${clusterName ?? "cluster"} — ${dateStr}`;
  pdf.setFontSize(14);
  pdf.text(title, 40, 30);

  // Add captured image
  const img = new Image();
  img.src = pngDataUrl;
  await new Promise<void>((resolve) => {
    img.onload = () => {
      pdf.addImage(pngDataUrl, "PNG", 40, headerHeight, captureWidth, captureHeight);
      resolve();
    };
    img.onerror = () => resolve();
  });

  // Footer
  const nodeCount = viewport.querySelectorAll(".react-flow__node").length;
  pdf.setFontSize(8);
  pdf.text(
    `Generated by Kubilitics | ${viewMode ?? "namespace"} view | ${nodeCount} resources | ${dateStr}`,
    40, pageHeight - 15
  );

  // Download
  const nsPart = selectedNamespaces && selectedNamespaces.size > 0
    ? `-${Array.from(selectedNamespaces).slice(0, 3).join("-")}`
    : "";
  const ts = Date.now();
  const filename = `${clusterName ?? "cluster"}${nsPart}-${viewMode ?? "namespace"}-${ts}.pdf`;
  pdf.save(filename);
}
