/**
 * PDF export for topology visualization.
 * Uses the same scale-1 viewport capture as PNG/SVG, then embeds in a
 * dynamically-sized PDF page.
 */
import { EXPORT } from "../constants/designTokens";

export async function exportTopologyPDF(
  clusterName?: string,
  viewMode?: string,
  selectedNamespaces?: Set<string>
): Promise<void> {
  const viewport = document.querySelector(".react-flow__viewport") as HTMLElement | null;
  if (!viewport) {
    console.warn("No React Flow viewport found for PDF export");
    return;
  }

  // Dynamically import dependencies
  const [{ toPng }, { jsPDF }] = await Promise.all([
    import("html-to-image"),
    import("jspdf"),
  ]);

  // Compute node bounds for scale-1 capture (same as PNG/SVG)
  const nodeEls = viewport.querySelectorAll(".react-flow__node");
  if (nodeEls.length === 0) return;

  let minX = Infinity, minY = Infinity, maxX = -Infinity, maxY = -Infinity;
  nodeEls.forEach((el) => {
    const node = el as HTMLElement;
    const style = node.style.transform || "";
    const match = style.match(/translate\((-?[\d.]+)px,\s*(-?[\d.]+)px\)/);
    if (match) {
      const x = parseFloat(match[1]);
      const y = parseFloat(match[2]);
      minX = Math.min(minX, x);
      minY = Math.min(minY, y);
      maxX = Math.max(maxX, x + node.offsetWidth);
      maxY = Math.max(maxY, y + node.offsetHeight);
    }
  });

  if (!isFinite(minX)) return;

  const contentW = maxX - minX;
  const contentH = maxY - minY;
  const padding = EXPORT.dynamicPadding(contentW, contentH);
  const captureWidth = Math.ceil(contentW + padding * 2);
  const captureHeight = Math.ceil(contentH + padding * 2);

  // Capture at scale 1
  const pngDataUrl = await toPng(viewport, {
    backgroundColor: EXPORT.backgroundColor,
    pixelRatio: 1, // 1x is enough for PDF — PDF handles resolution internally
    width: captureWidth,
    height: captureHeight,
    quality: 1.0,
    style: {
      transform: `translate(${-minX + padding}px, ${-minY + padding}px) scale(1)`,
      transformOrigin: "top left",
    },
    filter: (node: HTMLElement) => {
      const cn = node.className?.toString() ?? "";
      if (cn.includes("react-flow__minimap")) return false;
      if (cn.includes("react-flow__controls")) return false;
      if (cn.includes("react-flow__background")) return false;
      return true;
    },
  });

  // Dynamic page size — fit content with 40px margin for header/footer
  const headerHeight = 50;
  const footerHeight = 30;
  const pageWidth = captureWidth + 80;
  const pageHeight = captureHeight + headerHeight + footerHeight + 40;

  const pdf = new jsPDF({
    orientation: pageWidth > pageHeight ? "landscape" : "portrait",
    unit: "px",
    format: [pageWidth, pageHeight],
  });

  // Header
  const dateStr = new Date().toLocaleDateString();
  const title = `Kubilitics Topology — ${clusterName ?? "cluster"} — ${dateStr}`;
  pdf.setFontSize(14);
  pdf.text(title, 40, 30);

  // Add captured image
  const img = new Image();
  img.src = pngDataUrl;
  await new Promise<void>((resolve) => {
    img.onload = () => {
      pdf.addImage(pngDataUrl, "PNG", 40, headerHeight, captureWidth, captureHeight);
      resolve();
    };
    img.onerror = () => resolve();
  });

  // Footer
  pdf.setFontSize(8);
  pdf.text(
    `Generated by Kubilitics | ${viewMode ?? "namespace"} view | ${nodeEls.length} resources | ${dateStr}`,
    40, pageHeight - 15
  );

  // Download
  const nsPart = selectedNamespaces && selectedNamespaces.size > 0
    ? `-${Array.from(selectedNamespaces).slice(0, 3).join("-")}`
    : "";
  const ts = Date.now();
  const filename = `${clusterName ?? "cluster"}${nsPart}-${viewMode ?? "namespace"}-${ts}.pdf`;
  pdf.save(filename);
}
