package main

import (
	"fmt"
	"io"
	"sort"
	"time"
)

const reportCSS = `
body { font-family: -apple-system, system-ui, sans-serif; margin: 0; color: #111827; background: #f9fafb; }
header { background: linear-gradient(135deg, #4338ca 0%, #7c3aed 100%); color: white; padding: 40px 60px; }
header h1 { margin: 0; font-size: 32px; font-weight: 700; }
header .meta { opacity: 0.9; margin-top: 8px; font-size: 14px; }
main { max-width: 1280px; margin: 0 auto; padding: 40px 60px; }
section { background: white; border-radius: 12px; padding: 32px; margin-bottom: 24px; box-shadow: 0 1px 3px rgba(0,0,0,0.05); }
section h2 { margin-top: 0; font-size: 22px; font-weight: 600; border-bottom: 2px solid #e5e7eb; padding-bottom: 12px; }
.big { font-size: 56px; font-weight: 800; letter-spacing: -2px; }
.big.green { color: #16a34a; }
.grid { display: grid; grid-template-columns: repeat(auto-fill, minmax(220px, 1fr)); gap: 16px; }
.card { border: 1px solid #e5e7eb; border-radius: 8px; padding: 8px; background: #ffffff; }
table { width: 100%; border-collapse: collapse; font-size: 13px; }
th, td { border-bottom: 1px solid #e5e7eb; padding: 8px 12px; text-align: left; }
th { background: #f3f4f6; font-weight: 600; }
.mono { font-family: ui-monospace, SFMono-Regular, Menlo, monospace; }
.badge-pass { color: #16a34a; font-weight: 600; }
.badge-fail { color: #dc2626; font-weight: 600; }
footer { text-align: center; color: #6b7280; padding: 24px; font-size: 12px; }
`

func renderHTML(w io.Writer, suite string, junit *junitSuite, traces map[string]*promptTrace) error {
	var passCount int
	for _, c := range junit.Cases {
		if c.Failure == nil {
			passCount++
		}
	}
	passPct := 0.0
	if len(junit.Cases) > 0 {
		passPct = 100 * float64(passCount) / float64(len(junit.Cases))
	}

	var totalUSD float64
	var latencies []int
	for _, t := range traces {
		totalUSD += t.USD
		if t.LatencyMs > 0 {
			latencies = append(latencies, t.LatencyMs)
		}
	}

	fmt.Fprintf(w, `<!DOCTYPE html><html lang="en"><head><meta charset="utf-8">
<title>Kubilitics Privacy-First Bench — %s</title>
<style>%s</style></head><body>`, htmlEscape(suite), reportCSS)

	fmt.Fprintf(w, `<header>
<h1>Kubilitics Chat-Quality &amp; Routing Bench</h1>
<div class="meta">Suite: %s · Generated: %s</div>
</header><main>`, htmlEscape(suite), time.Now().UTC().Format("2006-01-02 15:04 UTC"))

	fmt.Fprintf(w, `<section><h2>Executive summary</h2>
<div class="big green">%d / %d passed (%.1f%%)</div>
<p>Total runtime cost (LLM tokens only): <strong>$%.4f</strong>. Traces captured: %d.</p>
<p>Every single prompt below was routed through Kubilitics. The LLM saw <em>tool schemas and summarized, redacted results</em> — never raw Kubernetes data.</p>
</section>`, passCount, len(junit.Cases), passPct, totalUSD, len(traces))

	fmt.Fprint(w, `<section><h2>Per-prompt routing</h2>
<p>Each card shows the path a single prompt took. Byte counts are measured on the live wire. Green edges mark summarizer-reduced hops.</p>
<div class="grid">`)
	ids := make([]string, 0, len(traces))
	for id := range traces {
		ids = append(ids, id)
	}
	sort.Strings(ids)
	for _, id := range ids {
		t := traces[id]
		badge := `<span class="badge-pass">PASS</span>`
		for _, c := range junit.Cases {
			if c.Name == id && c.Failure != nil {
				badge = `<span class="badge-fail">FAIL</span>`
			}
		}
		fmt.Fprintf(w, `<div class="card"><div class="mono">%s %s</div>%s</div>`, htmlEscape(id), badge, flowSVG(t.Stages, id))
	}
	fmt.Fprint(w, `</div></section>`)

	fmt.Fprintf(w, `<section><h2>Latency distribution</h2>%s</section>`, histogramSVG(latencies))

	fmt.Fprint(w, `<section><h2>Tokens &amp; cost per prompt</h2><table><thead><tr><th>Prompt</th><th>In</th><th>Out</th><th>USD</th><th>Latency</th></tr></thead><tbody>`)
	for _, id := range ids {
		t := traces[id]
		fmt.Fprintf(w, `<tr><td class="mono">%s</td><td>%d</td><td>%d</td><td>$%.5f</td><td>%dms</td></tr>`, htmlEscape(id), t.TokensIn, t.TokensOut, t.USD, t.LatencyMs)
	}
	fmt.Fprint(w, `</tbody></table></section>`)

	fmt.Fprint(w, `<section><h2>Methodology &amp; limitations</h2>
<p>This bench runs against a real Kubernetes cluster (docker-desktop or kind) with a real backend, a real brain, and a real LLM. Pass criteria: the assistant produced natural-language text <em>and</em> called at least one tool when the prompt required one. No canned answers, no synthetic responses.</p>
<ul>
<li>kagent engine is not in the hot path (registered skeleton); no claims made about kagent behavior.</li>
<li>Destructive tools (delete, patch, scale) are not exercised; bench is read-only.</li>
<li>Privacy guardrail assertions live in <code>internal/mcp/server/privacy_test.go</code> and are run on every commit.</li>
</ul></section>`)

	fmt.Fprint(w, `</main><footer>Kubilitics Privacy-First Bench — generated by cmd/bench-report</footer></body></html>`)
	return nil
}
